# Generated by Django 5.2.7 on 2025-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Укажите, активен или отключен пользователь",
                verbose_name="Активен или отключен",
            ),
        ),
    ]
