# Generated by Django 5.2.7 on 2025-11-07 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_title",
                    models.CharField(
                        help_text="Укажите название товара",
                        max_length=300,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "product_model",
                    models.CharField(
                        blank=True,
                        help_text="Укажите модель товара",
                        max_length=150,
                        null=True,
                        verbose_name="Модель товара",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание товара",
                        null=True,
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "product_launch_date",
                    models.DateField(
                        help_text="Укажите дату выхода товара на рынок",
                        verbose_name="Дата выхода товара на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_title",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=300,
                        verbose_name="Название",
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail", "Розничная сеть"),
                            ("entrepreneur", "Индивидуальный предприниматель"),
                        ],
                        default="retail",
                        help_text="Выберите тип продавца",
                        max_length=12,
                        verbose_name="Тип продавца",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите электронную почту",
                        max_length=254,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Укажите страну",
                        max_length=150,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Укажите город",
                        max_length=150,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Укажите улицу",
                        max_length=200,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="Укажите номер дома",
                        max_length=15,
                        null=True,
                        verbose_name="Номер дома",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Укажите задолженность перед поставщиком",
                        max_digits=11,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите время создания",
                        verbose_name="Время создания",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        choices=[(0, "Уровень 0"), (1, "Уровень 1"), (2, "Уровень 2")],
                        default=0,
                        help_text="Укажите уровень иерархии",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Уровень иерархии",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите товар",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="retail.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="retail.seller",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продавец",
                "verbose_name_plural": "Продавцы",
            },
        ),
    ]
