# Generated by Django 5.2.7 on 2025-11-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_title",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=300,
                        verbose_name="Название",
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail", "Розничная сеть"),
                            ("entrepreneur", "Индивидуальный предприниматель"),
                        ],
                        default="retail",
                        help_text="Выберите тип продавца",
                        max_length=12,
                        verbose_name="Тип продавца",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите электронную почту",
                        max_length=254,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Укажите страну",
                        max_length=150,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Укажите город",
                        max_length=150,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Укажите улицу",
                        max_length=200,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="Укажите номер дома",
                        max_length=15,
                        null=True,
                        verbose_name="Номер дома",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите время создания",
                        verbose_name="Время создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продавец",
                "verbose_name_plural": "Продавцы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_title",
                    models.CharField(
                        help_text="Укажите название товара",
                        max_length=300,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "product_model",
                    models.CharField(
                        blank=True,
                        help_text="Укажите модель товара",
                        max_length=150,
                        null=True,
                        verbose_name="Модель товара",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание товара",
                        null=True,
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "product_launch_date",
                    models.DateField(
                        help_text="Укажите дату выхода товара на рынок",
                        verbose_name="Дата выхода товара на рынок",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        help_text="Укажите производителя (завод или ИП)",
                        limit_choices_to={
                            "seller_type__in": ["factory", "entrepreneur"]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        to="retail.seller",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="SellerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Укажите цену товара",
                        max_digits=10,
                        verbose_name="Цена товара",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество товара",
                        verbose_name="Количество товара",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Укажите задолженность за этот товар",
                        max_digits=11,
                        verbose_name="Задолженность за этот товар",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        default=0,
                        help_text="Укажите уровень иерархии для этой связи",
                        verbose_name="Уровень иерархии для этой связи",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Укажите товар",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retail.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Укажите продавца",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retail.seller",
                        verbose_name="Продавец",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Укажите поставщика этого товара",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplied_items",
                        to="retail.seller",
                        verbose_name="Поставщик этого товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь продавца с товаром",
                "verbose_name_plural": "Связи продавцов с товарами",
                "unique_together": {("seller", "product", "supplier")},
            },
        ),
    ]
