# Generated by Django 5.2.7 on 2025-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerproduct",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите задолженность за этот товар с копейками в формате 0.00",
                max_digits=11,
                verbose_name="Задолженность за этот товар",
            ),
        ),
    ]
