# Generated by Django 5.2.7 on 2025-11-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите цену",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
