# Generated by Django 5.2.7 on 2025-11-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0002_alter_sellerproduct_debt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_title", "id"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="seller",
            options={
                "ordering": ["seller_title", "id"],
                "verbose_name": "Продавец",
                "verbose_name_plural": "Продавцы",
            },
        ),
    ]
