# Generated by Django 5.2.7 on 2025-11-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0003_alter_product_options_alter_seller_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sellerproduct",
            options={
                "ordering": ["seller", "product"],
                "verbose_name": "Связь продавца с товаром",
                "verbose_name_plural": "Связи продавцов с товарами",
            },
        ),
    ]
