# Generated by Django 5.2.7 on 2025-11-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0004_alter_sellerproduct_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerproduct",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите поставщика этого товара",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplied_items",
                to="retail.seller",
                verbose_name="Поставщик этого товара",
            ),
        ),
    ]
